### ISSUE TITLE
Problem with handling projection

### ISSUE THREAD

**Issue by saberraz** [erpas/serval#12]
1	Traceback (most recent call last):
			  File "C:/Users/Saber/.qgis2/python/plugins\Serval\serval.py", line 610, in prepare_gdal_raster
			    self.gdal_raster.SetProjection(str(proj_wkt))
			  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\osgeo\gdal.py", line 1651, in SetProjection
			    return _gdal.Dataset_SetProjection(self, *args)
			RuntimeError: NITF only supports WGS84 geographic and UTM projections.

**Comment by erpas** [comment]
We do not use directly GDAL bindings for raster opening. Closing the issue.
