### ISSUE TITLE
KeyError when loading layer into QGIS

### ISSUE THREAD

**Issue by AlisterH** [erpas/serval#46]
Serval produces an error message like this when certain layers are loaded into QGIS:
```An error has occurred while executing Python code: 

KeyError: 
Traceback (most recent call last):
  File "C:\Users/alister/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Serval\serval.py", line 734, in set_active_raster
    supported, unsupported_type = self.handler.write_supported()
  File "C:\Users/alister/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Serval\raster_handler.py", line 79, in write_supported
    msg = f"{dtypes[self.provider.dataType(nr)]['name']} (band {nr})"
KeyError: 


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.32.3-Lima Lima, 67d46100b5 
```
Here is an example file:
[Stage 1 results extent - Copy.zip](https://github.com/lutraconsulting/serval/files/13011312/Stage.1.results.extent.-.Copy.zip)

**Comment by erpas** [comment]
Thanks for reporting the problem!

Fixed in v. 3.32.0 - to be released soon.
